"""
Run store — structured persistence layer for notebook run artifacts.

Every notebook execution writes into a unique directory::

    runs/
      pipeline/
        20260414_112301_a3f2/   ← one run
          manifest.json         ← full structured record for this run
          benchmark_results.csv
          preprocessing_benchmark.png
          regressor_benchmark.png
          backbone_benchmark.png
          bayes_tuning.png
        history.csv             ← one row per run, all runs for this name
        metrics_history.png     ← regenerated by metrics_viz after each run
      bayes/
        20260414_113045_b1e9/
          manifest.json
          bayes_tuning_dp_steel.png
        history.csv
        metrics_history.png
      demo/
        20260414_115500_c7d1/
          manifest.json
          model_comparison.png
          ...
        history.csv
        metrics_history.png

Public API
----------
RunStore(name, base_dir)
  .start()                         → run_dir Path, run_id str
  .write_manifest(data)            → Path
  .copy_artifact(src)              → Path
  .append_history(row_dict)        → Path
  .run_dir                         → Path to current run directory
  .run_id                          → str  e.g. "20260414_112301_a3f2"
  .history_path                    → Path to history.csv
"""

from __future__ import annotations

import csv
import json
import shutil
import uuid
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

_RUNS_DIR = Path(__file__).parent.parent / "runs"


class RunStore:
    """
    Manages a named family of runs (e.g. ``"pipeline"``, ``"bayes"``, ``"demo"``).

    Parameters
    ----------
    name :
        Short identifier for the notebook family.  Used as the sub-directory
        name under ``base_dir``.  Should be one of ``"pipeline"``,
        ``"bayes"``, or ``"demo"`` but any slug is accepted.
    base_dir :
        Root runs directory.  Defaults to ``runs/`` next to ``src/``.
    """

    def __init__(
        self,
        name: str,
        base_dir: Optional[Union[str, Path]] = None,
    ) -> None:
        self.name = name
        self.base_dir = Path(base_dir).resolve() if base_dir else _RUNS_DIR
        self._run_dir: Optional[Path] = None
        self._run_id: Optional[str] = None

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def run_dir(self) -> Path:
        if self._run_dir is None:
            raise RuntimeError("Call start() before accessing run_dir.")
        return self._run_dir

    @property
    def run_id(self) -> str:
        if self._run_id is None:
            raise RuntimeError("Call start() before accessing run_id.")
        return self._run_id

    @property
    def family_dir(self) -> Path:
        """``runs/<name>/``"""
        return self.base_dir / self.name

    @property
    def history_path(self) -> Path:
        """``runs/<name>/history.csv``"""
        return self.family_dir / "history.csv"

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def start(self) -> tuple[Path, str]:
        """
        Allocate a new run directory and return ``(run_dir, run_id)``.

        The run ID is ``<YYYYMMDD_HHMMSS>_<4-hex-chars>`` — timestamp-sortable
        and unique enough for a research workflow.

        Safe to call multiple times in the same Python session (each call
        creates a new directory).
        """
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        uid = uuid.uuid4().hex[:4]
        self._run_id = f"{ts}_{uid}"
        self._run_dir = self.family_dir / self._run_id
        self._run_dir.mkdir(parents=True, exist_ok=True)
        return self._run_dir, self._run_id

    # ------------------------------------------------------------------
    # Write helpers
    # ------------------------------------------------------------------

    def write_manifest(self, data: Dict[str, Any]) -> Path:
        """
        Write *data* as ``manifest.json`` inside the current run directory.

        Automatically adds ``run_id``, ``name``, and ``saved_at`` fields.
        Merges with any existing manifest (so you can call this incrementally).

        Returns the path written.
        """
        dest = self.run_dir / "manifest.json"
        existing: Dict = {}
        if dest.exists():
            with open(dest) as f:
                existing = json.load(f)

        existing.update(data)
        existing.setdefault("run_id", self.run_id)
        existing.setdefault("name", self.name)
        existing["saved_at"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        with open(dest, "w") as f:
            json.dump(existing, f, indent=2, default=_json_default)
        return dest

    def copy_artifact(self, src: Union[str, Path], dest_name: Optional[str] = None) -> Path:
        """
        Copy *src* into the current run directory.

        Parameters
        ----------
        src : Source file path.
        dest_name : Override filename in the run directory.  Defaults to the
            source filename.

        Returns the destination path.
        """
        src = Path(src)
        dest = self.run_dir / (dest_name or src.name)
        shutil.copy2(src, dest)
        return dest

    def append_history(self, row: Dict[str, Any]) -> Path:
        """
        Append one row to ``runs/<name>/history.csv``.

        Creates the file with a header on first call.  Column set is the union
        of all keys ever written — new columns get empty values in older rows
        when the file is loaded.

        Parameters
        ----------
        row : Dict of column→value for this run.  ``run_id`` and ``saved_at``
            are added automatically if absent.

        Returns the history CSV path.
        """
        row = dict(row)
        row.setdefault("run_id", self.run_id)
        row.setdefault("saved_at", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))

        path = self.history_path
        path.parent.mkdir(parents=True, exist_ok=True)

        write_header = not path.exists() or path.stat().st_size == 0

        # If file exists, read existing columns to keep consistent ordering
        existing_cols: List[str] = []
        if not write_header:
            with open(path, newline="") as f:
                reader = csv.reader(f)
                existing_cols = next(reader, [])

        # Merge: existing columns first, then any new ones from this row
        all_cols = list(existing_cols)
        for k in row:
            if k not in all_cols:
                all_cols.append(k)

        with open(path, "a", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=all_cols, extrasaction="ignore")
            if write_header:
                writer.writeheader()
            elif set(all_cols) != set(existing_cols):
                # New columns appeared — rewrite the whole file with updated header
                _rewrite_csv_with_new_cols(path, all_cols, row)
                return path
            writer.writerow(row)

        return path

    # ------------------------------------------------------------------
    # Convenience
    # ------------------------------------------------------------------

    def print_summary(self) -> None:
        """Print a one-line summary of the current run."""
        print(f"[RunStore] name={self.name}  run_id={self.run_id}")
        print(f"           run_dir={self.run_dir}")
        print(f"           history={self.history_path}")


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _json_default(obj: Any) -> Any:
    """JSON serialiser fallback for numpy scalars and similar."""
    try:
        import numpy as np
        if isinstance(obj, (np.integer,)):
            return int(obj)
        if isinstance(obj, (np.floating,)):
            return float(obj)
        if isinstance(obj, np.ndarray):
            return obj.tolist()
    except ImportError:
        pass
    return str(obj)


def _rewrite_csv_with_new_cols(
    path: Path,
    new_cols: List[str],
    new_row: Dict[str, Any],
) -> None:
    """
    Re-write *path* with *new_cols* as the header, appending *new_row*.
    Existing rows get empty strings for any previously-absent columns.
    """
    rows: List[Dict] = []
    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for r in reader:
            rows.append(dict(r))
    rows.append(new_row)
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=new_cols, extrasaction="ignore")
        writer.writeheader()
        for r in rows:
            writer.writerow(r)
